/* Copyright (C) 2021 Cisco Systems, Inc. and/or its affiliates. All rights reserved. */

#ifndef __CLAMAV_RUST_H
#define __CLAMAV_RUST_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "libclamav/others.h"


bool clrs_log_init(void);

void clrs_eprint(const char *c_buf);

uintptr_t generate_phash(const uint8_t *file_bytes,
                         uintptr_t file_size,
                         uint8_t *phash,
                         uintptr_t phash_len);

#endif /* __CLAMAV_RUST_H */
